-- Corrigir a tabela cursos_competencias para alinhar com a migration
ALTER TABLE cursos_competencias
  MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN competenciaId INT NOT NULL,
  MODIFY COLUMN titulo VARCHAR(255) NOT NULL,
  MODIFY COLUMN descricao TEXT NULL,
  MODIFY COLUMN capaUrl VARCHAR(500) NULL,
  MODIFY COLUMN ordem INT NOT NULL DEFAULT 0,
  MODIFY COLUMN isActive INT NOT NULL DEFAULT 1,
  MODIFY COLUMN createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
