CREATE TABLE `performance_uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`uploadedBy` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileKey` varchar(512),
	`fileUrl` text,
	`totalRecords` int NOT NULL DEFAULT 0,
	`processedRecords` int NOT NULL DEFAULT 0,
	`skippedRecords` int NOT NULL DEFAULT 0,
	`newAlunos` int NOT NULL DEFAULT 0,
	`updatedRecords` int NOT NULL DEFAULT 0,
	`status` enum('processing','completed','error') NOT NULL DEFAULT 'processing',
	`errorMessage` text,
	`summary` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `performance_uploads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `student_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alunoId` int,
	`externalUserId` varchar(100) NOT NULL,
	`userName` varchar(255) NOT NULL,
	`userEmail` varchar(320),
	`lastAccess` varchar(100),
	`turmaId` int,
	`externalTurmaId` varchar(100),
	`turmaName` varchar(255),
	`competenciaId` int,
	`externalCompetenciaId` varchar(100),
	`competenciaName` varchar(255),
	`dataInicio` varchar(100),
	`dataConclusao` varchar(100),
	`totalAulas` int DEFAULT 0,
	`aulasDisponiveis` int DEFAULT 0,
	`aulasConcluidas` int DEFAULT 0,
	`aulasEmAndamento` int DEFAULT 0,
	`aulasNaoIniciadas` int DEFAULT 0,
	`aulasAgendadas` int DEFAULT 0,
	`progressoTotal` int DEFAULT 0,
	`cargaHorariaTotal` varchar(20),
	`cargaHorariaConcluida` varchar(20),
	`progressoAulasDisponiveis` int DEFAULT 0,
	`avaliacoesDiagnostico` int DEFAULT 0,
	`mediaAvaliacoesDiagnostico` decimal(5,2),
	`avaliacoesFinais` int DEFAULT 0,
	`mediaAvaliacoesFinais` decimal(5,2),
	`avaliacoesDisponiveis` int DEFAULT 0,
	`avaliacoesRespondidas` int DEFAULT 0,
	`avaliacoesPendentes` int DEFAULT 0,
	`avaliacoesAgendadas` int DEFAULT 0,
	`mediaAvaliacoesDisponiveis` decimal(5,2),
	`mediaAvaliacoesRespondidas` decimal(5,2),
	`concluidoDentroPrazo` varchar(100),
	`concluidoEmAtraso` varchar(100),
	`naoConcluidoDentroPrazo` varchar(100),
	`naoConcluidoEmAtraso` varchar(100),
	`uploadId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `student_performance_id` PRIMARY KEY(`id`)
);
