CREATE TABLE `announcements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`content` text,
	`type` enum('webinar','course','activity','notice','news') NOT NULL DEFAULT 'notice',
	`imageUrl` text,
	`imageKey` varchar(512),
	`actionUrl` varchar(500),
	`actionLabel` varchar(100),
	`programId` int,
	`targetAudience` enum('all','sebrae_to','sebrae_acre','embrapii','banrisul') DEFAULT 'all',
	`priority` int NOT NULL DEFAULT 0,
	`publishAt` timestamp,
	`expiresAt` timestamp,
	`isActive` int NOT NULL DEFAULT 1,
	`webinarId` int,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `announcements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_webinars` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`theme` varchar(255),
	`speaker` varchar(255),
	`speakerBio` text,
	`eventDate` timestamp NOT NULL,
	`duration` int DEFAULT 60,
	`meetingLink` varchar(500),
	`youtubeLink` varchar(500),
	`cardImageUrl` text,
	`cardImageKey` varchar(512),
	`programId` int,
	`targetAudience` enum('all','sebrae_to','sebrae_acre','embrapii','banrisul') DEFAULT 'all',
	`status` enum('draft','published','completed','cancelled') NOT NULL DEFAULT 'draft',
	`reminderSent` int NOT NULL DEFAULT 0,
	`reminderSentAt` timestamp,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduled_webinars_id` PRIMARY KEY(`id`)
);
